// LOCALHOST
############################################ Contacts ############################################
############################################          ############################################

### GET ALL CONTACTS
GET http://localhost:8080/contacts
### GET CONTACT BY ID
GET http://localhost:8080/contacts/634ac4c1ceddc78dc81b030e
### CREATE CONTACT 
POST http://localhost:8080/contacts/ HTTP/1.1 
content-type: application/json

{
"firstName":"Maddison", "lastName":"Snyder", "email":"madd@test.com", "birthday":"12/10/2010", "phone":"381-966-7951", "address":"3533 Fairway Cir", "city":"Spanish Fork", "state": "UT", "zip": 84660
}

### UPDATE CONTACT 
PUT http://localhost:8080/contacts/6345d13226e91456b2cffc00 HTTP/1.1
content-type: application/json

{
"firstName":"Joshua", "lastName":"Snyder", "email":"snyderjosh@test.com", "birthday":"01/23/1983", "phone":"381-960-7941", "address":"3533 Fairway Cir", "city":"Spanish Fork", "state": "UT", "zip": 84660
}

### DELETE contact
DELETE http://localhost:8080/contacts/633998317e01e692acc8db29 HTTP/1.1

############################################ Pets ############################################
############################################      ############################################

### GET ALL PETS
GET http://localhost:8080/pets
### GET PET BY ID
GET http://localhost:8080/pets/634ad40bc6894380de46df8d
### CREATE PET 
POST http://localhost:8080/pets/ HTTP/1.1 
content-type: application/json

{
"ownerId":"Not implented Yet", "name":"TestDog", "type":"Cat", "sex":"female", "color":"Calico", "birthday":"12/10/2020", "license":"1", "habitat":"Inside", "cost":72.77, "trained": "0"
}

### UPDATE PET 
PUT http://localhost:8080/pets/634ad40bc6894380de46df8d HTTP/1.1
content-type: application/json

{
"ownerId":"FOO", "name":"TestDog", "type":"Cat", "sex":"female", "color":"Calico", "birthday":"12/10/2020", "license":"1", "habitat":"Inside", "cost":72.77, "trained": "0"
}

### DELETE PET
DELETE http://localhost:8080/pets/634ad40bc6894380de46df8d HTTP/1.1

// PRODUCTION Deploy

############################################ Contacts ############################################
############################################          ############################################
### GET ALL CONTACTS
GET https://project2-rq2e.onrender.com/contacts
### GET CONTACT BY ID
GET https://project2-rq2e.onrender.com/contacts/632f87066354770fc88f0288
### CREATE CONTACT
GET https://project2-rq2e.onrender.com/contacts HTTP/1.1 
content-type: application/json

{
"firstName":"TestFirstName", "lastName":"TestLastName", "email":"Create@test.com", "favoriteColor":"Test", "birthday":"06/19/2000"
}
### UPDATE CONTACT 
PUT https://project2-rq2e.onrender.com/contacts/633876ffa52c4c6a870799e8 HTTP/1.1
content-type: application/json

{
"firstName":"TestFirstUpdate", "lastName":"TestLastUpdate", "email":"test@gmail.com", "favoriteColor":"Green", "birthday":"12/12/20"
}
### DELETE contact
DELETE https://project2-rq2e.onrender.com/contacts/633876ffa52c4c6a870799e8 HTTP/1.1

############################################ Pets ############################################
############################################      ############################################

### GET ALL PETS
GET https://project2-rq2e.onrender.com/pets
### GET PET BY ID
GET https://project2-rq2e.onrender.com/632f87066354770fc88f0288
### CREATE PET 
POST https://project2-rq2e.onrender.com/pets HTTP/1.1 
content-type: application/json

{
"ownerId":"Not implented Yet", "name":"TestDog", "type":"Cat", "sex":"female", "color":"Calico", "birthday":"12/10/2020", "license":"1", "habitat":"Inside", "cost":72.77, "trained": "0"
}

### UPDATE PET 
PUT https://project2-rq2e.onrender.com/pets/633876ffa52c4c6a870799e8 HTTP/1.1
content-type: application/json

{
"ownerId":"FOO", "name":"TestDog", "type":"Cat", "sex":"female", "color":"Calico", "birthday":"12/10/2020", "license":"1", "habitat":"Inside", "cost":72.77, "trained": "0"
}

### DELETE PET
DELETE https://project2-rq2e.onrender.com/pets/633876ffa52c4c6a870799e8 HTTP/1.1